name: Test Docker Login

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Verify Docker Login
        run: docker info
